# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       yaml-cpp

# >> macros
# << macros

Summary:    A YAML parser and emitter for C++
Version:    0.5.1
Release:    1
Group:      Development/Libraries
License:    MIT
URL:        http://code.google.com/p/yaml-cpp/
Source0:    %{name}-%{version}.tar.xz
Source100:  yaml-cpp.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  cmake
BuildRequires:  boost-devel

%description
yaml-cpp is a YAML parser and emitter in C++ written around the YAML 1.2 spec.


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   boost-devel
Requires:   pkgconfig

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.


%prep
%setup -q -n src

# >> setup
# Fix eol
sed -i 's/\r//' license.txt
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DYAML_CPP_BUILD_TOOLS=0

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%doc license.txt
%{_libdir}/*.so.*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/yaml-cpp/
%{_libdir}/*.so
%{_libdir}/pkgconfig/*.pc
# >> files devel
# << files devel
